name: Release

on:
  push:
    tags: ['v*']

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            platform: mac
          - os: ubuntu-latest
            platform: linux
          - os: windows-latest
            platform: win
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v6
        with:
          node-version: '22'

      - name: Install
        run: npm ci
        env:
          PUPPETEER_SKIP_DOWNLOAD: 'true'

      - name: Build
        run: npm run dist:${{ matrix.platform }}
        env:
          PUPPETEER_SKIP_DOWNLOAD: 'true'
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload to release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            release/*.dmg
            release/*.dmg.blockmap
            release/*.zip
            release/*.zip.blockmap
            release/*.exe
            release/*.exe.blockmap
            release/*.AppImage
            release/*.deb
            release/latest*.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
